[build]
  publish = "."

[[headers]]
  for = "/results.json"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    Cache-Control = "public, max-age=0, must-revalidate"
